# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
#从 Rails 4 开始，默认存储机制是 EncryptedCookieStore。EncryptedCookieStore 会先对会话进行加密，再储存到 cookie 中。这么做可以防止用户访问和篡改 cookie 的内容。因此，会话也成为储存数据的更安全的地方。加密时需要使用 config/secrets.yml 文件中储存的服务器端密钥 secrets.secret_key_base。
development:
  secret_key_base: c942caed82f8cb50a662cef6ed22c71d2005f56a967eaed6c439588615a41e96c50a2a032400fff5d90936dee4db555268b6afde05df8a5a4d786ac0769df3eb

test:
  secret_key_base: 644efd71757d8a6848568620cfa8df7fc7198affd4a8ba9651b9fbd332c35e0563de5435b2f4baa1843be5abda1474797bf5b4f0c8e01bb4294dfa421ea3f81b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
